project_name: slsa-provenance

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

builds:
  - id: binary
    dir: cmd/slsa-provenance
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 8
    ldflags:
      - "{{ .Env.LDFLAGS }}"

archives:
  - id: archive
    format: tar.gz
    replacements:
      darwin: macOS
    files:
      - LICENSE*
      - README*
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "rblit/{{ .ProjectName }}:v{{ .Version }}"
      - "rblit/{{ .ProjectName }}:{{ .FullCommit }}"
      - "ghcr.io/royblit/{{ .ProjectName }}:v{{ .Version }}"
      - "ghcr.io/royblit/{{ .ProjectName }}:{{ .FullCommit }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.vendor=SLSA test"
    extra_files:
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - "cmd"
      - "lib"
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  draft: true
  prerelease: auto
