project_name: slsa-provenance

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

builds:
  - id: binary
    dir: cmd/slsa-provenance
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 8
    ldflags:
      - "{{ .Env.LDFLAGS }}"

archives:
  - id: archive
    format: tar.gz
    replacements:
      darwin: macOS
    files:
      - LICENSE*
      - README*
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "philipssoftware/{{ .ProjectName }}:v{{ .Version }}"
      - "philipssoftware/{{ .ProjectName }}:{{ .FullCommit }}"
      - "ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}"
      - "ghcr.io/philips-labs/{{ .ProjectName }}:{{ .FullCommit }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.vendor=Koninklijke Philips N.V."
    extra_files:
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - "cmd"
      - "lib"

docker_manifests:
  - name_template: 'philipssoftware/{{ .ProjectName }}:v{{ .Version }}'
    image_templates:
      - 'philipssoftware/{{ .ProjectName }}:v{{ .Version }}-amd64'
      - 'philipssoftware/{{ .ProjectName }}:v{{ .Version }}-arm64'
  - name_template: 'ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}'
    image_templates:
      - 'ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}-amd64'
      - 'ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}-arm64'
  - name_template: 'philipssoftware/{{ .ProjectName }}:{{ .FullCommit }}'
    image_templates:
      - 'philipssoftware/{{ .ProjectName }}:v{{ .Version }}-amd64'
      - 'philipssoftware/{{ .ProjectName }}:v{{ .Version }}-arm64'
  - name_template: 'ghcr.io/philips-labs/{{ .ProjectName }}:{{ .FullCommit }}'
    image_templates:
      - 'ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}-amd64'
      - 'ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}-arm64'

signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - 'sign'
      - '${artifact}'

snapshot:
  name_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
